/*
  # Add messages table for sending messages

  1. New Tables
    - `messages`
      - `id` (bigint, primary key) - Unique identifier for messages
      - `content` (text) - Text content of the message
      - `media_type` (text) - Type of media (text, image, audio, video, document)
      - `media_url` (text) - URL to the media file
      - `media_caption` (text) - Caption for the media
      - `status` (text) - Status of the message (pending, sent, failed, cancelled)
      - `created_at` (timestamptz) - Creation timestamp
  
  2. Security
    - Enable RLS on `messages` table
    - Add policies for authenticated users to perform CRUD operations
*/

-- Create the messages table
CREATE TABLE IF NOT EXISTS messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content text,
  media_type text NOT NULL,
  media_url text,
  media_caption text,
  status text NOT NULL DEFAULT 'pending',
  created_at timestamptz DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- Create policies for authenticated users
CREATE POLICY "Allow all operations for authenticated users on messages"
  ON messages
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);